project_id = "cocuhrhazafkyskeplzj"

[functions.create-checkout-session]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.save-lead-data]
verify_jwt = false

[functions.chat-agent]
verify_jwt = false

[functions.voice-agent]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.elevenlabs-voice]
verify_jwt = false

[functions.elevenlabs-signed-url]
verify_jwt = false

[functions.openai-text-to-speech]
verify_jwt = false

[functions.save-agent-lead]
verify_jwt = false

[functions.save-agent-chat]
verify_jwt = false

[functions.send-payment-link]
verify_jwt = false