// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cocuhrhazafkyskeplzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvY3VocmhhemFma3lza2VwbHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjYyNjUsImV4cCI6MjA3MTkwMjI2NX0.UvF2mJwqGsQvUjubvk3DCi4VdzQAv6sOCSXs4ZzPAwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});